### ISSUE TITLE
Add concurrency parameter

### ISSUE THREAD

**Issue by maxpowel** [applauncher-team/celery_bundle#5]
Allow the configuration parameter for concurrency, ej

```
celery:
  broker: {CELERY_BROKER}
  result_backend: {CELERY_BACKEND}
  worker: True
  concurrency: 10
```
